using System.Collections;
using System.Collections.Generic;
using System.Numerics;
using UnityEngine;
using UnityEngine.SocialPlatforms;

namespace Renge.PPB {

	public class ProgressBarProperties {
		public const string Value = "_Value";
		public const string CenterFill = "_CenterFill";
		public const string BorderWidth = "_BorderWidth";
		public const string InnerBorderWidth = "_InnerBorderWidth";
		public const string BorderRadius = "_BorderRadius";
		public const string BorderRadiusOffset = "_BorderRadiusOffset";
		public const string SegmentCount = "_SegmentCount";
		public const string SegmentSpacing = "_SegmentSpacing";
		public const string InnerRoundingPercent = "_InnerRoundingPercent";
		public const string InnerColor = "_InnerColor";
		public const string BackgroundColor = "_BackgroundColor";
		public const string BorderColor = "_BorderColor";
		public const string InnerBorderColor = "_InnerBorderColor";
		public const string OverlayColor = "_OverlayColor";
		public const string InnerTexture = "_InnerTexture";
		public const string InnerTextureOpacity = "_InnerTextureOpacity";
		public const string InnerTextureTiling = "_InnerTextureTiling";
		public const string InnerTextureOffset = "_InnerTextureOffset";
		public const string InnerTextureRotation = "_InnerTextureRotation";
		public const string InnerGradient = "_InnerGradient";
		public const string InnerGradientEnabled = "_InnerGradientEnabled";
		public const string InnerGradientRotation = "_InnerGradientRotation";
		public const string ValueAsGradientTimeInner = "_ValueAsGradientTimeInner";
		public const string OverlayTexture = "_OverlayTexture";
		public const string OverlayTextureOpacity = "_OverlayTextureOpacity";
		public const string OverlayTextureTiling = "_OverlayTextureTiling";
		public const string OverlayTextureOffset = "_OverlayTextureOffset";
		public const string BorderTexture = "_BorderTexture";
		public const string BorderTextureTiling = "_BorderTextureTiling";
		public const string BorderTextureOffset = "_BorderTextureOffset";
		public const string BorderTextureOpacity = "_BorderTextureOpacity";
		public const string BackgroundTexture = "_BackgroundTexture";
		public const string BackgroundTextureTiling = "_BackgroundTextureTiling";
		public const string BackgroundTextureOffset = "_BackgroundTextureOffset";
		public const string BackgroundGradientRotation = "_BackgroundGradientRotation";
		public const string BackgroundTextureOpacity = "_BackgroundTextureOpacity";
		public const string BackgroundGradient = "_BackgroundGradient";
		public const string BackgroundTextureScaleWithSegments = "_BackgroundTextureScaleWithSegments";
		public const string BackgroundGradientEnabled = "_BackgroundGradientEnabled";
		public const string ValueAsGradientTimeBackground = "_ValueAsGradientTimeBackground";
		public const string PulsateWhenLow = "_PulsateWhenLow";
		public const string PulseActivationThreshold = "_PulseActivationThreshold";
		public const string PulseSpeed = "_PulseSpeed";
		public const string PulseRamp = "_PulseRamp";
		public const string PulseColor = "_PulseColor";
		public const string VariableWidthCurve = "_VariableWidthCurve";
		public const string AdjustBorderRadiusToWidthCurve = "_AdjustBorderRadiusToWidthCurve";
		public const string Slant = "_Slant";
		public const string FlipbookFPS = "_FlipbookFPS";
		public const string InnerFlipbookDim = "_InnerFlipbookDim";
		public const string OverlayFlipbookDim = "_OverlayFlipbookDim";
		public const string BorderFlipbookDim = "_BorderFlipbookDim";
		public const string BackgroundFlipbookDim = "_BackgroundFlipbookDim";
		public const string ValueMaskOffset = "_ValueMaskOffset";
		public const string OffsetTextureWithValue = "_OffsetTextureWithValue";
		public const string ValueShadowColor = "_ValueShadowColor";
		public const string ValueShadowSize = "_ValueShadowSize";
		public const string ValueShadowFalloff = "_ValueShadowFalloff";
		public const string BorderShadowColor = "_BorderShadowColor";
		public const string BorderShadowSize = "_BorderShadowSize";
		public const string BorderShadowFalloff = "_BorderShadowFalloff";
		public const string ValueInsetShadowColor = "_ValueInsetShadowColor";
		public const string ValueInsetShadowSize = "_ValueInsetShadowSize";
		public const string ValueInsetShadowFalloff = "_ValueInsetShadowFalloff";
		public const string BorderInsetShadowColor = "_BorderInsetShadowColor";
		public const string BorderInsetShadowSize = "_BorderInsetShadowSize";
		public const string BorderInsetShadowFalloff = "_BorderInsetShadowFalloff";
		public const string Radius = "_Radius";
		public const string Arc = "_Arc";
		public const string Width = "_Width";
		public const string CircleLength = "_CircleLength";
		public const string UIScaling = "_UIScaling";
		public const string CustomScale = "_CustomScale";
	}
}